# This is a basic workflow to help you get started with Actions

name: CI

on:
  issues:
    types: [ opened ]

jobs:
  test_hoge:
    runs-on: ubuntu-latest

    steps:
    - name: Run a multi-line script
      env:
        ISSUE_TITLE: ${{ github.event.issue.title }}
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        echo ${ISSUE_TITLE}
