name: catkin_make@kinetic
on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - 'develop'

jobs:
  docker_build:
    runs-on: ubuntu-latest
    name: build docker image
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: /tmp/docker-registry
          key: docker-registry-buildkit-${{ github.sha }}
          restore-keys: docker-registry-buildkit-
      - name: build
        run: |
          docker run -d -p 5000:5000 --restart=always --name registry -v /tmp/docker-registry:/var/lib/registry registry:2
          npx wait-on tcp:5000
          docker build -t hogehoge --cache-from=localhost:5000/hogehoge --build-arg BUILDKIT_INLINE_CACHE=1 ${GITHUB_WORKSPACE}
          docker tag hogehoge localhost:5000/hogehoge
          docker push localhost:5000/hogehoge
