name: catkin_make@kinetic
on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - 'develop'

jobs:
  docker_build:
    runs-on: ubuntu-latest
    name: build docker image
    steps:
      - name: Set env GITHUB_DOCKER_REPO
        run: |
          echo "${{ github.repository }}"
          echo "::set-env name=GITHUB_DOCKER_REPO::docker.pkg.github.com/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')"
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        with:
          path: buildx-cache
          key: docker-buildx-${{ hashFiles('Dockerfile', 'hoge/*') }}
          restore-keys: docker-buildx-
      - if: steps.cache.outputs.cache-hit == 'true'
        run: |
          echo "cache hit!"
      - uses: crazy-max/ghaction-docker-buildx@v3
      - run: |
          set -eux

          CACHE_FROM_ARGS=""
          if [ -d buildx-cache ]; then
            CACHE_FROM_ARGS="--cache-from type=local,src=buildx-cache"
          fi

          docker buildx build \
            ${CACHE_FROM_ARGS} \
            --cache-to type=local,mode=max,dest=buildx-cache \
            --target base \
            -t hogehoge:latest \
            .