name: catkin_make@kinetic
on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - 'develop'

jobs:
  docker_build:
    runs-on: ubuntu-latest
    name: build docker image
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: buildx-cache
          key: docker-buildx-${{ hashFiles('Dockerfile') }}
          restore-keys: docker-buildx-
      - if: steps.cache.outputs.cache-hit == 'true'
        id: hogehoge
        run: |
          echo "::set-output name=CACHE_FROM_ARGS::--cache-from type=local,src=buildx-cache"
      - uses: crazy-max/ghaction-docker-buildx@v3
      - run: |
          set -eux
          docker buildx build \
            --file Dockerfile \
            ${{ steps.hogehoge.output.CACHE_FROM_ARGS }} \
            --cache-to type=local,mode=max,dest=buildx-cache \
            -t hogehoge:latest \
            .