name: catkin_make@kinetic
on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - 'develop'

jobs:
  docker_build:
    runs-on: ubuntu-latest
    name: build docker image
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: buildx-cache
          key: docker-buildx-${{ github.sha }}
          restore-keys: docker-buildx-
      - run: |
          set -eux
          FROM_ARG=""
          if [ -e buildx-cache/index.json ]; then
            FROM_ARG="--cache-from type=local,src=buildx-cache"
          fi
          docker buildx build \
            --file Dockerfile \
            $FROM_ARG \
            --cache-to type=local,mode=max,dest=buildx-cache \
            -t hogehoge:latest \
            .