name: catkin_make@kinetic
on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - 'develop'

env:
  REPO: docker.pkg.github.com/takumikodamaatmakino/test

jobs:
  docker_build:
    runs-on: ubuntu-latest
    name: build docker image
    steps:
      - uses: actions/checkout@v2
      - name: Calc hash
        run: echo "::set-env name=SRC_HASH::${{ hashFiles('Dockerfile', 'hoge/*') }}"
      - name: Login to GitHub docker registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - name: Pull image
        id: pull
        run: |
          if docker pull ${REPO}/hogehoge:${SRC_HASH}; then
            echo "::set-output name=pulled::true"
          else
            docker pull ${REPO}/hogehoge:latest || true
            echo "::set-output name=pulled::false"
          fi
      - name: Build image
        if: steps.pull.outputs.pulled == 'false'
        run: |
          docker build \
            --target base \
            -t ${REPO}/hogehoge:${SRC_HASH} \
            -t ${REPO}/hogehoge:latest \
            .

          docker images

          docker push ${REPO}/hogehoge:${SRC_HASH}
          docker push ${REPO}/hogehoge:latest
      - name: Test
        run: |
          docker run -v ${GITHUB_WORKSPACE}:/root/iassist_ros ${REPO}/hogehoge:latest cat /root/iassist_ros/hoge.txt