name: Prepare for release
on:
  issues:
    types: [ opened ]

env:
  ISSUE_TITLE_PATTERN: "^release\\ (v[0-9]+\\.[0-9]+\\.[0-9]+)$"
  VERSION_FILE_NAME: version

jobs:
  prepare:
    name: Check release version
    description: |
      Check if the issue title is for a release.
      If so, the version will be stored in ${{ {job}.outputs.ver }}.
    runs-on: ubuntu-latest
    outputs:
      ver: ${{ steps.check_issue_title.outputs.ver }}
    steps:
      - name: Check issue title
        id: check_issue_title
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
        run: |
          if [[ ${ISSUE_TITLE} =~ ${ISSUE_TITLE_PATTERN} ]]; then \
            ver="${BASH_REMATCH[1]}"; \
            echo "::set-output name=ver::${ver}"; \
          fi

  new_branch:
    name: Create branch/PR
    description: |
      Create new release branch and PullRequests.
      PullRequests are for master and develop.
    runs-on: ubuntu-latest
    needs: [ prepare ]
    if: ${{ needs.prepare.outputs.ver != '' }}
    env:
      VERSION: ${{ needs.prepare.outputs.ver }}
      BRANCH_NAME: release/${{ needs.prepare.outputs.ver }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ISSUE_NUMBER: ${{ github.event.issue.number }}
    steps:
      - uses: actions/checkout@v2
      - name: git config user.name/email
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Create/Push release branch
        run: |
          git checkout -b ${BRANCH_NAME} origin/develop
          echo -n "${VERSION}" > ./${VERSION_FILE_NAME}
          git add ./${VERSION_FILE_NAME}
          git commit -m "prepare for release ${VERSION}"
          git push -u origin ${BRANCH_NAME}
      - name: Create PR for master branch
        run: |
          curl -XPOST https://api.github.com/repos/TakumiKodamaAtMakino/test/pulls \
            -H "Authorization: token ${GITHUB_TOKEN}" \
            -d '{
              "title":"'${VERSION}'",
              "body":"Close #'${ISSUE_NUMBER}'",
              "base":"master",
              "head":"'${BRANCH_NAME}'"
            }'
      - name: Create PR for develop branch
        run: |
            curl -XPOST https://api.github.com/repos/TakumiKodamaAtMakino/test/pulls \
            -H "Authorization: token ${GITHUB_TOKEN}" \
            -d '{
              "title":"'${VERSION}' to develop",
              "body":"Close #'${ISSUE_NUMBER}'",
              "base":"develop",
              "head":"'${BRANCH_NAME}'"
            }'
